import java.util.ArrayList;

/**
 * Arinah Karim     ankarim
 * CSCI-C 343 / Fall 2020
 * 9/7/2020
 */
public class TweetClass {
    private String author;
    private String content;

    public TweetClass(String a, String c){
        author = a;
        content = c;
    }

    public String getAuthor(){
        return author;
    }

    public String getContent(){
        return content;
    }

    public boolean contains(String s){
        if (content.contains(s)){
            return true;
        }
        else{
            return false;
        }
    }

    public static void main(String[] args){
//        TweetClass t = new TweetClass("someperson", "It is now possible to learn about a person's mobility preferences from data generated by their smartphone");
//        System.out.println(t.getContent());
//        System.out.println(t.getAuthor());
//        System.out.println(t.contains("zbd"));
//        System.out.println(t.contains("now"));
    }
}
